services:
  wxbot:
    image: localhost/kakie/wxbot-rs:dev
    container_name: wxbot
    environment:
      APP_CONF_PATH: /app/prod_config.toml
      APP_WEB_PORT: 9000
    ports:
      - "9000:9000"
    entrypoint: ["/bin/bash", "-c"]
    command: ["/app/target/release/wxbot-rs"]
    networks:
      botnet:
        ipv4_address: 172.20.20.2

networks:
  botnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.20.0/28
          gateway: 172.20.20.1
